# Generated by Django 4.0.6 on 2022-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
