# Generated by Django 4.0.6 on 2022-08-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'Nosotross', 'verbose_name_plural': 'Nosotros'},
        ),
    ]
