# Generated by Django 4.0.6 on 2022-08-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'Nosotros', 'verbose_name_plural': 'Nosotros'},
        ),
    ]
