# Generated by Django 4.0.6 on 2022-08-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='creation_date',
        ),
    ]
