# Generated by Django 4.0.6 on 2022-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
